apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 681863550751.dkr.ecr.us-east-1.amazonaws.com/docker-containers:flask-app-latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 81  
          env:
            - name: DBHOST
              value: "mysql-service"  
            - name: DBUSER
              value: "root"  
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: db-secret  
                  key: password    
            - name: DATABASE
              value: "employees"  
            - name: DBPORT
              value: "3306"  
            - name: BACKGROUND_IMAGE
              value: "https://eks-pr-bucket.s3.us-east-1.amazonaws.com/Kubernetes.jpeg"  
            - name: GROUP_NAME
              value: "GROUP11"  
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret  
                  key: AWS_ACCESS_KEY_ID  
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret  
                  key: AWS_SECRET_ACCESS_KEY  
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret  
                  key: AWS_SESSION_TOKEN  
            - name: APP_COLOR
              value: "lime"  
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 81
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 81
          #   initialDelaySeconds: 10
          #   periodSeconds: 20            

