apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc  # PVC name
  namespace: final  # Ensure it’s in the correct namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: aws-ebs-csi