apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: final  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      serviceAccountName: clo835
      containers:
        - name: mysql-db
          image: 681863550751.dkr.ecr.us-east-1.amazonaws.com/docker-containers:mysql-app-latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret 
                  key: password
            - name: MYSQL_DATABASE
              value: "employees"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc  
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      annotations:
        volume.beta.kubernetes.io/storage-class: gp2
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
      storageClassName: aws-ebs-csi