apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: clo835-cluster
  region: us-west-2
nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        imageBuilder: true
    kubeconfig:
      name: clo835-cluster
  namespaces:
    - final

# To create the cluster with eksctl, you would run:
# eksctl create cluster -f eks/eks-cluster.yaml
