---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: clo835-cluster
  region: "us-east-1"
  version: "1.29"

availabilityZones: ["us-east-1a" ,"us-east-1b"]
iam:
  serviceRoleARN: arn:aws:iam::681863550751:role/LabRole
managedNodeGroups:
- name: nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::681863550751:role/LabRole      
      withAddonPolicies:
        imageBuilder: true
    kubeconfig:
      name: clo835-cluster
  namespaces:
    - final
    
# eksctl create cluster -f eks/eks_config.yaml
