apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.0.0
  values:
    git:
      url: "git@github.com:deveshgupta7/EKS_StatefulApplication.git"
      branch: main
